spring:
  application:
    name: AutoGraderService
  datasource:
    username: ${DB_USER}
    password: ${DB_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/exam_service?serverTimezone=UTC
  jpa:
    open-in-view: false
    show-sql: true
    hibernate:
      ddl-auto: update


server:
  port: 8082

jwt:
  secret: ${JWT_SECRET}
